import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  RotateCcw,
  CheckCircle2,
  Clock,
  BookOpen,
  Video,
  Sparkles,
  ArrowRight,
  TrendingUp,
  FileCheck,
  ChevronDown,
  ChevronUp,
  ShieldCheck
} from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const RecoveryPlanView: React.FC = () => {
  const {
    recoveryPlan,
    completeRecoveryStep,
    setCurrentTab,
    selectedSubject,
    startQuiz
  } = useApp();

  const [expandedStep, setExpandedStep] = useState<number>(1);

  if (!recoveryPlan) {
    return (
      <div className="max-w-2xl mx-auto py-12 px-4 animate-in fade-in duration-300">
        <div className="p-8 sm:p-10 rounded-3xl bg-white border border-slate-200/90 shadow-xl space-y-6 text-center">
          <div className="w-16 h-16 rounded-2xl bg-blue-50 text-blue-600 border border-blue-200 mx-auto flex items-center justify-center">
            <RotateCcw className="w-8 h-8" />
          </div>

          <div className="space-y-2">
            <span className="px-3 py-1 rounded-full text-xs font-bold bg-blue-50 text-blue-700 border border-blue-100">
              Targeted Remediation Module
            </span>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
              No Recovery Plans Needed Yet
            </h2>
            <p className="text-xs sm:text-sm text-slate-500 max-w-md mx-auto leading-relaxed">
              When an assessment isolates a specific conceptual misconception, TeachLens generates an evidence-grounded 5-step recovery plan with guided walkthroughs and practice questions.
            </p>
          </div>

          <div className="pt-2">
            <button
              onClick={() => {
                if (selectedSubject) {
                  startQuiz(selectedSubject.id);
                } else {
                  setCurrentTab('quiz');
                }
              }}
              className="px-6 py-3 rounded-2xl bg-blue-600 hover:bg-blue-700 text-white font-extrabold text-xs shadow-md shadow-blue-500/25 transition-all inline-flex items-center gap-2"
            >
              <span>Take Diagnostic Assessment</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    );
  }

  const completedCount = recoveryPlan.steps.filter((s) => s.completed).length;
  const progressPercent = Math.round((completedCount / recoveryPlan.steps.length) * 100);

  const getStepIcon = (type: string) => {
    switch (type) {
      case 'review':
        return BookOpen;
      case 'video':
        return Video;
      case 'guided_example':
        return Sparkles;
      case 'targeted_practice':
        return RotateCcw;
      case 'reassessment':
        return TrendingUp;
      default:
        return FileCheck;
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-300">
      
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-bold uppercase tracking-wider text-blue-600 bg-blue-50 px-2.5 py-0.5 rounded-full border border-blue-100">
              Personalized Remediation Module
            </span>
            <span className="text-slate-300">•</span>
            <span className="text-xs text-slate-500">Auto-Generated by AI Gap Engine</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
            Your Recovery Path
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Systematic micro-steps to repair conceptual gaps and regain verified mastery.
          </p>
        </div>

        {/* Estimated Recovery Time Badge */}
        <div className="p-3 rounded-2xl bg-white border border-blue-200/80 shadow-xs flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center">
            <Clock className="w-5 h-5" />
          </div>
          <div>
            <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-wider block">
              Estimated Recovery Time
            </span>
            <span className="text-sm font-extrabold text-blue-900">
              {recoveryPlan.estimatedMinutes || 15} minutes
            </span>
          </div>
        </div>
      </div>

      {/* Progress Metric Header Card */}
      <div className="p-6 rounded-3xl bg-gradient-to-r from-blue-50/80 via-white to-sky-50/50 border border-blue-200/70 shadow-xs flex flex-col sm:flex-row items-center justify-between gap-6">
        <div className="space-y-1 text-center sm:text-left">
          <div className="flex items-center justify-center sm:justify-start gap-2">
            <h3 className="text-lg font-bold text-slate-900">
              {recoveryPlan.conceptName}
            </h3>
            <span className="text-xs font-bold px-2 py-0.5 rounded-md bg-blue-100 text-blue-800">
              Step {completedCount + 1} of {recoveryPlan.steps.length}
            </span>
          </div>
          <p className="text-xs text-slate-500">
            {completedCount} of {recoveryPlan.steps.length} milestones achieved ({progressPercent}% finished). Completing unlocks Comeback Points.
          </p>
        </div>

        {/* Progress Bar */}
        <div className="w-full sm:w-64 space-y-1.5">
          <div className="flex justify-between text-xs font-bold text-slate-700">
            <span>Progress</span>
            <span className="text-blue-600">{progressPercent}%</span>
          </div>
          <div className="w-full bg-slate-200/80 rounded-full h-2.5 overflow-hidden">
            <motion.div
              className="bg-blue-600 h-full rounded-full"
              initial={{ width: 0 }}
              animate={{ width: `${progressPercent}%` }}
              transition={{ duration: 0.8 }}
            />
          </div>
        </div>
      </div>

      {/* Vertical Animated Timeline */}
      <div className="relative pl-6 sm:pl-10 space-y-6 before:absolute before:left-3 sm:before:left-5 before:top-4 before:bottom-4 before:w-0.5 before:bg-slate-200">
        {recoveryPlan.steps.map((step) => {
          const Icon = getStepIcon(step.type);
          const isExpanded = expandedStep === step.stepNumber;

          return (
            <motion.div
              key={step.stepNumber}
              initial={{ opacity: 0, x: -10 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.3, delay: step.stepNumber * 0.05 }}
              className="relative"
            >
              {/* Timeline Node Dot */}
              <div
                onClick={() => completeRecoveryStep(step.stepNumber)}
                className={`absolute -left-6 sm:-left-10 top-5 w-6 h-6 sm:w-8 sm:h-8 rounded-full flex items-center justify-center cursor-pointer transition-all ${
                  step.completed
                    ? 'bg-emerald-600 text-white shadow-md shadow-emerald-500/20'
                    : 'bg-white border-2 border-slate-300 text-slate-400'
                }`}
              >
                {step.completed ? (
                  <CheckCircle2 className="w-4 h-4 sm:w-5 sm:h-5" />
                ) : (
                  <span className="text-xs font-extrabold">{step.stepNumber}</span>
                )}
              </div>

              {/* Step Card */}
              <div
                className={`rounded-3xl border transition-all ${
                  step.completed
                    ? 'bg-white/90 border-slate-200/80 shadow-xs'
                    : 'bg-white border-blue-200 shadow-xs ring-1 ring-blue-400/20'
                }`}
              >
                {/* Header row */}
                <div
                  onClick={() => setExpandedStep(isExpanded ? 0 : step.stepNumber)}
                  className="p-5 sm:p-6 flex items-center justify-between cursor-pointer"
                >
                  <div className="flex items-center gap-3.5">
                    <div
                      className={`w-10 h-10 rounded-2xl flex items-center justify-center shrink-0 ${
                        step.completed
                          ? 'bg-emerald-50 text-emerald-600'
                          : 'bg-blue-50 text-blue-600'
                      }`}
                    >
                      <Icon className="w-5 h-5" />
                    </div>

                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-[11px] font-bold text-blue-600 uppercase tracking-wider">
                          Step {step.stepNumber}
                        </span>
                        <span className="text-slate-300">•</span>
                        <span className="text-xs text-slate-400">{step.durationMinutes} mins</span>
                      </div>
                      <h4 className="text-base font-bold text-slate-900 mt-0.5">
                        {step.title}
                      </h4>
                    </div>
                  </div>

                  <div className="flex items-center gap-3">
                    {step.completed ? (
                      <span className="hidden sm:inline-block px-2.5 py-0.5 rounded-full text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-100">
                        Completed
                      </span>
                    ) : (
                      <span className="hidden sm:inline-block px-2.5 py-0.5 rounded-full text-xs font-bold bg-blue-50 text-blue-700 border border-blue-100">
                        Ready
                      </span>
                    )}

                    <button className="p-1 rounded-lg text-slate-400 hover:text-slate-600">
                      {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                    </button>
                  </div>
                </div>

                {/* Collapsible Content Body */}
                <AnimatePresence>
                  {isExpanded && (
                    <motion.div
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                      className="px-5 sm:px-6 pb-6 pt-1 border-t border-slate-100 text-xs sm:text-sm text-slate-600 space-y-4"
                    >
                      <p className="leading-relaxed text-slate-600">
                        {step.content?.summary}
                      </p>

                      {/* Rule & Formula Callout */}
                      {step.content?.keyRule && (
                        <div className="p-4 rounded-2xl bg-blue-50/70 border border-blue-100">
                          <span className="text-[10px] font-bold uppercase tracking-wider text-blue-700 block mb-1">
                            Fundamental Formula
                          </span>
                          <div className="font-mono text-sm font-bold text-blue-900">
                            {step.content.keyRule}
                          </div>
                          {step.content.formula && (
                            <p className="mt-2 text-xs text-slate-600 font-sans">
                              {step.content.formula}
                            </p>
                          )}
                        </div>
                      )}

                      {/* Walkthrough Steps */}
                      {step.content?.walkthroughSteps && (
                        <div className="space-y-2.5">
                          {step.content.walkthroughSteps.map((ws, idx) => (
                            <div
                              key={idx}
                              className="p-3.5 rounded-xl bg-slate-50 border border-slate-100"
                            >
                              <div className="font-bold text-slate-800 text-xs mb-0.5">
                                {ws.step}
                              </div>
                              <div className="text-xs text-slate-600">
                                {ws.explanation}
                              </div>
                            </div>
                          ))}
                        </div>
                      )}

                      {/* Action buttons inside step */}
                      <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
                        {!step.completed ? (
                          <button
                            onClick={() => completeRecoveryStep(step.stepNumber)}
                            className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs transition-colors flex items-center gap-1.5"
                          >
                            <CheckCircle2 className="w-3.5 h-3.5" />
                            <span>Mark Step as Complete</span>
                          </button>
                        ) : (
                          <span className="text-xs font-semibold text-emerald-700 flex items-center gap-1">
                            <CheckCircle2 className="w-4 h-4" />
                            Step mastered
                          </span>
                        )}

                        {step.stepNumber === 5 && (
                          <button
                            onClick={() => setCurrentTab('quiz')}
                            className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs shadow-sm flex items-center gap-1.5"
                          >
                            <span>Take Reassessment</span>
                            <ArrowRight className="w-3.5 h-3.5" />
                          </button>
                        )}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </motion.div>
          );
        })}
      </div>

      {/* Bottom CTA */}
      <div className="p-6 rounded-3xl bg-slate-900 text-white flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <h4 className="text-base font-bold">Ready to log your Comeback Score?</h4>
          <p className="text-xs text-slate-300 mt-0.5">
            Take a diagnostic reassessment to document your mastery gain and climb the Comeback Leaderboard.
          </p>
        </div>
        <button
          onClick={() => setCurrentTab('quiz')}
          className="px-6 py-3 rounded-2xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold shadow-md shadow-blue-500/20 transition-all flex items-center gap-2 whitespace-nowrap"
        >
          <span>Start Reassessment</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </div>

    </div>
  );
};
